### ISSUE TITLE
Process lookup error

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ideonate/bokeh-root-cmd#4]
I've installed `bokeh_root_cmd==0.1.1` on my jupyterhub.

In my `config.yml` file ([link](https://zero-to-jupyterhub.readthedocs.io/en/stable/administrator/advanced.html?highlight=jupyterhub_config.py#arbitrary-extra-code-and-configuration-in-jupyterhub-config-py)) I've added 

```bash
hub:
  extraConfig:
    ...
    cds-extra-frameworks: |
      c.CDSDashboardsConfig.extra_presentation_types = ["flask", "panel"]

      c.VariableMixin.extra_presentation_launchers = {
          "flask": {
              "args": [
                  "--destport=0",
                  "python3",
                  "{-}m",
                  "flask_gunicorn_cmd.main",
                  "{presentation_path}",
                  "{--}port={port}",
              ]
          },
          "panel": {
              "args": [
                  "--destport=0",
                  "python3",
                  "{-}m",
                  "bokeh_root_cmd.main",
                  "{presentation_path}",
                  "{--}port={port}",
                  "{--}allow-websocket-origin={origin_host}",
                  "{--}panel",
                  "--ready-check-path=/ready-check",
              ]
          },
      }
```

The two extra frameworks show up in the menu 

![image](https://user-images.githubusercontent.com/42288570/129861991-b184481e-223f-4383-8b2d-e10f38ab15c1.png)

But when I "save" I get the error message after the image has built and started.

```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.9/site-packages/jhsingle_native_proxy/websocket.py", line 102, in get
    return await self.http_get(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 849, in http_get
    return await self.proxy(self.port, path)
  File "/opt/conda/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 843, in proxy
    return await self.oauth_proxy(port, path)
  File "/opt/conda/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 798, in oauth_proxy
    return await self.core_proxy(port, path)
  File "/opt/conda/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 829, in core_proxy
    if not await self.ensure_process():
  File "/opt/conda/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 762, in ensure_process
    await proc.kill()
  File "/opt/conda/lib/python3.9/site-packages/simpervisor/process.py", line 167, in kill
    return await self._signal_and_wait(signal.SIGKILL)
  File "/opt/conda/lib/python3.9/site-packages/simpervisor/process.py", line 140, in _signal_and_wait
    self.proc.send_signal(signum)
  File "/opt/conda/lib/python3.9/asyncio/subprocess.py", line 138, in send_signal
    self._transport.send_signal(signal)
  File "/opt/conda/lib/python3.9/asyncio/base_subprocess.py", line 145, in send_signal
    self._check_proc()
  File "/opt/conda/lib/python3.9/asyncio/base_subprocess.py", line 142, in _check_proc
    raise ProcessLookupError()
ProcessLookupError
```

![image](https://user-images.githubusercontent.com/42288570/129862104-fdde24b2-e977-42b0-bead-51e8b747ebcc.png)

Any suggestions/ fixes would be appreciated. Thanks.

**Comment by MarcSkovMadsen** [comment]
Flask works though

![image](https://user-images.githubusercontent.com/42288570/129866650-374e64ad-5ff3-4235-b599-b1ef9b3c9a3a.png)

**Comment by MarcSkovMadsen** [comment]
Panel works if I change the framework back to Bokeh. The problem is that bokeh does not serve all the css and js needed by Panel.

![image](https://user-images.githubusercontent.com/42288570/129866924-df573086-9d12-4e44-a91f-c31ecb986c6d.png)

**Comment by MarcSkovMadsen** [comment]
If I run the below in a terminal

```
python3 -m bokeh_root_cmd.main /home/jovyan/./shared/panel-app.ipynb --port=2000
```

and open `https://<domain>/mt-workspace/user/masma/proxy/2000/` (important with final `/`) I see

![image](https://user-images.githubusercontent.com/42288570/129870198-ffe14d49-3415-414f-a363-fd1883c810ac.png)

**Comment by MarcSkovMadsen** [comment]
If I run

```bash
python3 -m bokeh_root_cmd.main /home/jovyan/./shared/panel-app.ipynb --port=2000 --server=panel
```

and open https://<domain>/mt-workspace/user/masma/proxy/2000/ it works

![image](https://user-images.githubusercontent.com/42288570/129870675-84ed4c48-98ea-44a7-9ac1-bc1668595af6.png)

**Comment by MarcSkovMadsen** [comment]
ahh. I should probably change `{--}panel` to `{--server}=panel` in the config file.

**Comment by MarcSkovMadsen** [comment]
I tried to but I still get the error

![image](https://user-images.githubusercontent.com/42288570/129873585-ffa6c68c-f2c4-4d60-9eaf-eca7fc39260f.png)

**Comment by MarcSkovMadsen** [comment]
I changed the config.yaml to

```bash
"panel": {
              "args": [
                "--destport=0",
                "python3",
                "{-}m",
                "bokeh_root_cmd.main",
                "{presentation_path}",
                "{--}port={port}",
                "{--}allow-websocket-origin={origin_host}",
                "--ready-check-path=/ready-check"
                ]
          },
```

![image](https://user-images.githubusercontent.com/42288570/129880709-d6266ba4-a52b-44d9-9a55-ea87a19f02f9.png)


So now my app is deployed under the framework name `panel`. But using the bokeh server.

**Comment by MarcSkovMadsen** [comment]
I can now see from the logs that I start containDS app from a dev image containing bokeh-root-cmd==0.1.1 but builds a (prod) image containing bokeh-root-cmd==0.1.0.

**Comment by MarcSkovMadsen** [comment]
I got it fixed and now it works. To summarize the issues that made it difficult to get working.

- My notebook was running on a dev image with `bokeh_root_cmd==0.1.1` it build and deployed a prod image with `bokeh_root_cmd==0.1.0`. Thus the `--server` option was not recognized. As this error is not shown to the user trying to deploy the pod its difficult to understand what the error is. I can see logs in Azure with a 15 mins delay. But I need to know how to query the logs using ksql which is not easy if you don't do it regularly. I don't have access to k8s logs directly via kubectl.
- I was in doubt whether it should be `--server=panel` or `{--}server=panel` and why. It's the latter I have to use.
- General lack of knowledge of the pipeline building and deploying our jupyter hub.
- The final step to get this working was a hard refresh of the browser. It was needed to load panel 0.12.1 js where the browser had cached panel 0.11.3 js.

![image](https://user-images.githubusercontent.com/42288570/129908539-69172ee3-f2eb-4eee-8da3-cc9ea64a70de.png)

This worked

```bash
"panel": {
              "args": [
                "--destport=0",
                "python3",
                "{-}m",
                "bokeh_root_cmd.main",
                "{presentation_path}",
                "{--}port={port}",
                "{--}allow-websocket-origin={origin_host}",
                "{--}server=panel",
                "--ready-check-path=/ready-check"
                ]
          },
```

**Comment by MarcSkovMadsen** [comment]
## Suggestion

Better error messages if the app deployed does not start would be really valuable. Including the full log.

I believe in many setups this would be a self service solution where users don't have access to logs from the underlying system. Thus making it very difficult to get things working if it does not. Leading to a high time to market instead of the opposite.

Useful debugging information would include

name of image
name and location of conda environment
python version
bokeh_root_cmd version
bokeh/ panel version
log

**Comment by danlester** [comment]
Thanks for all your comments here - really helpful for others, I'm sure. In general, better error reporting will always be helpful!

**Comment by danlester** [comment]
Closing due to inactivity automatically.
